from .AVWAP import AVWAP
from .BOLLINGERBANDSSHORT import BOLLINGER
from .PRICEMABANDSSHORT import PRICEMA
from .BTST import BTST


STRATEGY_REGISTRY = {
    'PRICEMABANDSSHORT': PRICEMA,
    'BTST': BTST,
    'BOLLINGERSHORT': BOLLINGER,
    'AVWAP': AVWAP
}
