from .AVWAP import AVWAP
from .BOLLINGERBANDSSHORT import BOLLINGER
from .PRICEMABANDSSHORT import PRICEMABANDSSHORT
from .BTST import BTST
from .ORBSTOCKS import ORBSTOCKS
from .AVWAP_V2 import AVWAPV2
from .PRICEMASHORT import PRICEMA
from .AVWAP_V3 import AVWAPV3
from .DONCHAINBTST import DONCHAIN
from .DONCHAINSHORT import DONCHAIN
from .DONCHAINDIRECTIONALSHORT import DONCHAINDIRECTIONAL
from .DONCHAININTRADAYSHORT import DONCHAININTRADAY
from .INTRADAYPULLBACK import INTRADAYPULLBACK
from .DONCHAINMEANRVERSIONLONG import DONCHAINMEAN

STRATEGY_REGISTRY = {
    'PRICEMABANDSSHORT': PRICEMABANDSSHORT,
    'BTST': BTST,
    'BOLLINGERBANDS': BOLLINGER,
    'AVWAP': AVWAP,
    'ORBSTOCKS': ORBSTOCKS,
    'AVWAPV2': AVWAPV2,
    'PRICEMASHORT': PRICEMA,
    'AVWAPV3': AVWAPV3,
    'DONCHAINBTST': DONCHAIN,
    'DONCHAINSHORT': DONCHAIN,
    'DONCHAINDIRECTIONAL': DONCHAINDIRECTIONAL,
    'DONCHAININTRADAYSHORT': DONCHAININTRADAY,
    'INTRADAYPULLBACK': INTRADAYPULLBACK,
    'DONCHAINMEANREVERSIONLONG': DONCHAINMEAN
}
