from .AVWAP import AVWAP
from .BOLLINGERBANDSSHORT import BOLLINGER
from .PRICEMABANDSSHORT import PRICEMA
from .BTST import BTST
from .ORBSTOCKS import ORBSTOCKS
from .AVWAP_V2 import AVWAPV2
from .PRICEMASHORT import PRICEMA
from .AVWAP_V3 import AVWAPV3

STRATEGY_REGISTRY = {
    'PRICEMABANDSSHORT': PRICEMA,
    'BTST': BTST,
    'BOLLINGERBANDS': BOLLINGER,
    'AVWAP': AVWAP,
    'ORBSTOCKS': ORBSTOCKS,
    'AVWAPV2': AVWAPV2,
    'PRICEMASHORT': PRICEMA,
    'AVWAPV3': AVWAPV3
}
